<?php

namespace Wellid\Cache;
class TestCacheableValidatable extends AbstractCacheableValidatable {
    public function getValue() {
        return 'mail@benedict\roe@ser.de';
    }
}
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-28 at 12:06:15.
 */
class AbstractCacheableValidatableTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractCacheableValidatable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TestCacheableValidatable();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::clearValidationResult
     * @todo   Implement testClearValidationResult().
     */
    public function testClearValidationResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::disableValidationCache
     * @todo   Implement testDisableValidationCache().
     */
    public function testDisableValidationCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::isValidationCacheEnabled
     * @todo   Implement testIsValidationCacheEnabled().
     */
    public function testIsValidationCacheEnabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
