<?php

namespace Wellid\Cache;
class TestCacheableValidatable extends AbstractCacheableValidatable {
    private $value = 4;
    
    public function setValue($value) {
        $this->value = $value;
    }
    
    public function getValue() {
        return $this->value;
    }
}
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-28 at 12:06:15.
 */
class AbstractCacheableValidatableTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TestCacheableValidatable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TestCacheableValidatable();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::clearValidationResult
     */
    public function testClearValidationResult() {
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->addValidator(new \Wellid\Validator\Min(100));
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->clearValidationResult();
        $this->assertFalse($this->object->validate()->hasPassed());
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::disableValidationCache
     * @todo   Implement testDisableValidationCache().
     */
    public function testDisableValidationCache() {
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->addValidator(new \Wellid\Validator\Min(100));
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->disableValidationCache();
        $this->assertFalse($this->object->validate()->hasPassed());
        $this->object->setValue(200);
        $this->assertTrue($this->object->validate()->hasPassed());
    }

    /**
     * @covers Wellid\Cache\AbstractCacheableValidatable::isValidationCacheEnabled
     */
    public function testIsValidationCacheEnabled() {
        $this->assertTrue($this->object->isValidationCacheEnabled());
        $this->object->disableValidationCache();
        $this->assertFalse($this->object->isValidationCacheEnabled());
    }

}
