<?php

namespace Wellid;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-21 at 15:31:04.
 */
class ValidationResultSetTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ValidationResultSet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidationResultSet();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\ValidationResultSet::add
     * @covers Wellid\ValidationResultSet::hasPassed
     * @covers Wellid\ValidationResultSet::hasErrors
     * @covers Wellid\ValidationResultSet::count
     * @covers Wellid\ValidationResultSet::firstError
     */
    public function testAdd() {
        $this->assertEquals(0, $this->object->count());

        $this->object->add(new ValidationResult(true));
        $this->object->add(new ValidationResult(true));

        $this->assertTrue($this->object->hasPassed());
        $this->assertEquals(2, $this->object->count());
        $this->assertNull($this->object->firstError());

        $this->object->add(new ValidationResult(false, 'test error message'));
        $this->assertFalse($this->object->hasPassed());
        $this->assertTrue($this->object->hasErrors());
        $this->assertEquals(3, $this->object->count());

        $this->assertEquals('test error message', $this->object->firstError()->getMessage());
    }

    /**
     * @covers Wellid\ValidationResultSet::addSet
     * @covers Wellid\ValidationResultSet::hasPassed
     * @covers Wellid\ValidationResultSet::hasErrors
     * @covers Wellid\ValidationResultSet::count
     * @covers Wellid\ValidationResultSet::firstError
     */
    public function testAddSet() {
        $this->object->addSet(new ValidationResultSet());
        $this->assertEquals(0, $this->object->count());

        $set = new ValidationResultSet();
        $set->add(new ValidationResult(true));
        $set->add(new ValidationResult(true));
        $this->object->addSet($set);
        $this->assertTrue($this->object->hasPassed());
        $this->assertEquals(2, $this->object->count());

        $set2 = new ValidationResultSet();
        $set2->add(new ValidationResult(false, 'test error message'));
        $set2->add(new ValidationResult(true));
        $this->object->addSet($set2);
        $this->assertFalse($this->object->hasPassed());
        $this->assertTrue($this->object->hasErrors());
        $this->assertEquals(4, $this->object->count());

        $set3 = new ValidationResultSet();
        $set3->add(new ValidationResult(false, 'another message'));
        $this->object->addSet($set3);
        $this->assertEquals('test error message', $this->object->firstError()->getMessage());
    }

    /**
     * @covers Wellid\ValidationResultSet::rewind
     * @covers Wellid\ValidationResultSet::next
     * @covers Wellid\ValidationResultSet::key
     * @covers Wellid\ValidationResultSet::current
     * @covers Wellid\ValidationResultSet::valid
     * @depends testAdd
     */
    public function testForeach() {
        $this->object->add(new ValidationResult(false, 'test error message'));
        $this->object->add(new ValidationResult(true));
        $this->object->add(new ValidationResult(true));
        $i = 0;
        foreach($this->object as $key => $validationResult) {
            $this->assertEquals($i, $key);
            $this->assertInstanceOf('Wellid\ValidationResult', $validationResult);
            if($i===0) $this->assertTrue($validationResult->isError());
            $i++;
        }
    }

    /**
     * @covers Wellid\ValidationResultSet::count
     * @depends testAdd
     */
    public function testCount() {
        $this->assertCount(0, $this->object);
        $this->object->add(new ValidationResult(true));
        $this->object->add(new ValidationResult(true));
        $this->assertCount(2, $this->object);
    }
    
    /**
     * @covers Wellid\ValidationResultSet::getErrorMessages
     * @depends testAdd
     */
    public function testGetErrorMessages() {
        $this->object->add(new ValidationResult(false, 'test error message'));
        $this->object->add(new ValidationResult(true));
        $this->object->add(new ValidationResult(false, 'test error message 2'));
        $this->object->add(new ValidationResult(true));
        $x = $this->object->getErrorMessages();
        $this->assertInternalType('array', $x);
        $this->assertCount(2, $x);
        $this->assertEquals('test error message', $x[0]);
    }
}
