<?php

namespace Wellid;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 16:30:01.
 */
class ValidatorHolderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ValidatorHolder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidatorHolder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\ValidatorHolder::addValidator
     */
    public function testAddValidator() {
        $this->assertEmpty($this->object->getValidators());

        $validator = new Validator\Boolean();

        $this->assertInstanceOf('Wellid\ValidatorHolderInterface', $this->object->addValidator($validator));

        $this->assertCount(1, $this->object->getValidators());

        $this->assertContainsOnlyInstancesOf(get_class($validator), $this->object->getValidators());
    }

    /**
     * @covers Wellid\ValidatorHolder::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wellid\ValidatorHolder::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wellid\ValidatorHolder::validateValue
     * @todo   Implement testValidateValue().
     */
    public function testValidateValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
