<?php

namespace Wellid\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-28 at 12:06:15.
 */
class FloatingPointTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FloatingPoint
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FloatingPoint;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\Validator\FloatingPoint::validate
     * @dataProvider booleanProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidate($value, $expected) {
        $result = $this->object->validate($value);

        $this->assertInstanceOf('Wellid\ValidationResult', $result);

        if ($expected) {
            $this->assertTrue($result->hasPassed());
            $this->assertFalse($result->isError());
            $this->assertEmpty($result->getMessage());
            $this->assertEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertEquals('passed', (string) $result);
        } else {
            $this->assertFalse($result->hasPassed());
            $this->assertTrue($result->isError());
            $this->assertNotEmpty($result->getMessage());
            $this->assertNotEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertNotEquals('passed', (string) $result);
        }
    }

    /**
     * Dataprovider for testValidate and testValidateBool
     * 
     * @return array()
     */
    public function booleanProvider() {
        return array(
            array(null, false),
            array('TRUE', false),
            array('abc', false),
            array(1, true),
            array(1.0, true),
            array(1.1, true),
            array(true, true),
            array(0.1, true),
            array(0.999, true),
            array(434, true),
            array('3', true),
            array('3.3', true),
            array('', false)
        );
    }

    /**
     * @covers Wellid\Validator\FloatingPoint::validate
     * @covers Wellid\Validator\FloatingPoint::__construct
     */
    public function testDecimal() {
        $fp0 = new FloatingPoint();
        $fp1 = new FloatingPoint(',');
        
        $this->assertTrue($fp0->validateBool('5.42'));
        $this->assertFalse($fp0->validateBool('5,42'));
        $this->assertFalse($fp0->validateBool('5_42'));
        $this->assertFalse($fp1->validateBool('5.42'));
        $this->assertTrue($fp1->validateBool('5,42'));
        $this->assertFalse($fp1->validateBool('5_42'));
        
    }
    
    /**
     * 
     */
    public function testArrayAndObjectValidation() {
        $this->assertFalse($this->object->validateBool(array(true)));
        $x = new \stdClass();
        $x->y = 'z';
        $this->assertFalse($this->object->validateBool($x));
    }

    /**
     * @covers Wellid\Validator\FloatingPoint::validateBool
     * @dataProvider booleanProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidateBool($value, $expected) {
        $this->assertEquals($expected, $this->object->validateBool($value));
    }

}
