<?php

namespace Wellid\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 16:30:18.
 */
class MacAddressTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MacAddress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MacAddress;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	/**
     * Dataprovider for testValidate and testValidateBool
     * 
     * @return array()
     */
    public function dataProvider() {
        return array(
            array(null, false),
            array('TRUE', false),
            array('abc', false),
            array(1, false),
            array('00:80:41:ae:fd:7e', true),
			array('00:80:41:ae:fd:7e:ab', false),
			array('00:gh:41:ae:fd:7e', false),
            array('', false)
        );
    }	
	
    /**
     * @covers Wellid\Validator\MacAddress::validate
     * @dataProvider dataProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidate($value, $expected) {
        $result = $this->object->validate($value);

        $this->assertInstanceOf('Wellid\ValidationResult', $result);

        if ($expected) {
            $this->assertTrue($result->hasPassed());
            $this->assertFalse($result->isError());
            $this->assertEmpty($result->getMessage());
            $this->assertEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertEquals('passed', (string) $result);
        } else {
            $this->assertFalse($result->hasPassed());
            $this->assertTrue($result->isError());
            $this->assertNotEmpty($result->getMessage());
            $this->assertNotEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertNotEquals('passed', (string) $result);
        }
    }

    /**
     * 
     */
    public function testArrayAndObjectValidation() {
        $this->assertFalse($this->object->validateBool(array(true)));
        $x = new \stdClass();
        $x->y = 'z';
        $this->assertFalse($this->object->validateBool($x));
    }

    /**
     * @covers Wellid\Validator\MacAddress::validateBool
     * @dataProvider dataProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidateBool($value, $expected) {
        $this->assertEquals($expected, $this->object->validateBool($value));
    }

}
