<?php

namespace Wellid\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-21 at 15:31:02.
 */
class MinLengthTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MinLength
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MinLength(7);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\Validator\MinLength::validate
     * @dataProvider stringProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidate($value, $expected) {
        $result = $this->object->validate($value);

        $this->assertInstanceOf('Wellid\ValidationResult', $result);

        if ($expected) {
            $this->assertTrue($result->hasPassed());
            $this->assertFalse($result->isError());
            $this->assertEmpty($result->getMessage());
            $this->assertEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertEquals('passed', (string) $result);
        } else {
            $this->assertFalse($result->hasPassed());
            $this->assertTrue($result->isError());
            $this->assertNotEmpty($result->getMessage());
            $this->assertNotEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertNotEquals('passed', (string) $result);
        }
    }

    /**
     * Dataprovider for testValidate and testValidateBool
     * 
     * @return array()
     */
    public function stringProvider() {
        return array(
            array(null, false),
            array(4, false),
            array(false, false),
            array('aaaa', false),
            array('Yellow1', true),
            array(12345678, true),
            array('87654321', true),
            array('sdf klöökl sdfsdf', true),
            array('00123456', true)
        );
    }

    /**
     * @covers Wellid\Validator\MinLength::validateBool
     * @dataProvider stringProvider
     * @param mixed $value
     * @param boolean $expected
     */
    public function testValidateBool($value, $expected) {
        $this->assertEquals($expected, $this->object->validateBool($value));
    }

    /**
     * @covers Wellid\Validator\MinLength::__construct
     */
    public function testExceptions() {
        $exceptionOkay = false;
        try {
            new MinLength(false);
        } catch (\Wellid\Exception\DataType $ex) {
            $exceptionOkay = true;
        }
        
        if(!$exceptionOkay) {
            $this->fail('Expected Exception was not thrown');
        }
        
        $exceptionOkay = false;
        try {
            new MinLength(-3);
        } catch (\Wellid\Exception\DataType $ex) {
            $exceptionOkay = true;
        }
        
        if(!$exceptionOkay) {
            $this->fail('Expected Exception was not thrown');
        }
        
        new MinLength(0);
    }      
}
