<?php

namespace Wellid\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-21 at 15:31:03.
 */
class PasswordTest extends \PHPUnit_Framework_TestCase {
    const EXPECT_EXCEPTION = 'x';
    /**
     * @var Password
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Password(password_hash('p4ssword', PASSWORD_DEFAULT));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Dataprovider for testValidate and testValidateBool
     * 
     * @return array()
     */
    public function dataProvider() {
        return array(
            array(null, self::EXPECT_EXCEPTION),
            array(true, self::EXPECT_EXCEPTION),
            array(false, self::EXPECT_EXCEPTION),
            array(1, self::EXPECT_EXCEPTION),
            array(array(), self::EXPECT_EXCEPTION),
            array(new \stdClass(), self::EXPECT_EXCEPTION),
            array('1', false),
            array('$b$bdfsdfjksdfl', false),
            array('p4ssword', true)
        );
    }
    
    /**
     * @covers Wellid\Validator\Password::validate
     * @dataProvider dataProvider
     * @param mixed $value
     * @param mixed $expected
     */
    public function testValidate($value, $expected) {
        try {
            $result = $this->object->validate($value);
        } catch (\Wellid\Exception\DataType $ex) {
            if ($expected !== self::EXPECT_EXCEPTION) {
                throw $ex;
            } else {
                return;
            }
        }

        $this->assertInstanceOf('Wellid\ValidationResult', $result);

        if ($expected) {
            $this->assertTrue($result->hasPassed());
            $this->assertFalse($result->isError());
            $this->assertEmpty($result->getMessage());
            $this->assertEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertEquals('passed', (string) $result);
        } else {
            $this->assertFalse($result->hasPassed());
            $this->assertTrue($result->isError());
            $this->assertNotEmpty($result->getMessage());
            $this->assertNotEquals(\Wellid\ValidationResult::ERR_NONE, $result->getCode());
            $this->assertNotEquals('passed', (string) $result);
        }
    }

    /**
     * @covers Wellid\Validator\Password::validateBool
     */
    public function testValidateBool() {
        $this->assertFalse($this->object->validateBool('abc'));
        $this->assertTrue($this->object->validateBool('p4ssword'));
    }
    
    /**
     * @covers Wellid\Validator\Password::__construct
     */
    public function testConstructor() {
        $exceptionOkay = false;
        try {
            new Password(123);
        } catch (\Wellid\Exception\DataType $ex) {
            $exceptionOkay = true;
        }
        if(!$exceptionOkay) {
            $this->fail('Expected DataType-Exception was not thrown');
        }
        $exceptionOkay = false;
        try {
            new Password('a');
        } catch (\Wellid\Exception\DataFormat $ex) {
            $exceptionOkay = true;
        }
        if(!$exceptionOkay) {
            $this->fail('Expected DataFormat-Exception was not thrown');
        }
    }

}
