<?php

namespace Wellid\Validator;

class TestSanitizable implements \Wellid\SanitorBridgeInterface{
    use \Wellid\SanitorBridgeTrait;
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-25 at 12:51:14.
 */
class SanitorMatchTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SanitorMatch
     */
    protected $object;
    
    /**
     *
     * @var \Wellid\SanitorBridgeInterface
     */
    protected $testSanitizable;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->testSanitizable = new TestSanitizable();
        $this->object = new SanitorMatch($this->testSanitizable);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wellid\Validator\SanitorMatch::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wellid\Validator\SanitorMatch::validateBool
     * @todo   Implement testValidateBool().
     */
    public function testValidateBool() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
