<?php

namespace WellidUsageExamples;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 19:20:33.
 */
class AccountBalanceValidatorsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AccountBalanceValidators
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccountBalanceValidators;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testValidatorSetup() {
        $this->assertGreaterThan(0, $this->object->getValidators());
        $this->assertContainsOnlyInstancesOf('Wellid\Validator\ValidatorInterface', $this->object->getValidators());
    }

}
