<?php

namespace WellidUsageExamples;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 19:20:33.
 */
class AccountBalanceTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AccountBalance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccountBalance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::createFromFloat
     * @todo   Implement testCreateFromFloat().
     */
    public function testCreateFromFloat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::validateBool
     * @todo   Implement testValidateBool().
     */
    public function testValidateBool() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::validateValue
     * @todo   Implement testValidateValue().
     */
    public function testValidateValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\AccountBalance::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
