<?php

namespace WellidUsageExamples;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 19:20:33.
 */
class SanitorWellidEmailExampleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SanitorWellidEmailExample
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_SESSION['validemail'] = 'mail@benedict\roeser.de';
        $_SESSION['invalidemail'] = '';
        $this->object = new SanitorWellidEmailExample;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getSanitizer
     */
    public function testGetSanitizer() {
        $this->assertEquals(FILTER_SANITIZE_EMAIL, $this->object->getSanitizer()->getSanitizeFilter());
        $this->assertEquals(FILTER_NULL_ON_FAILURE, $this->object->getSanitizer()->getSanitizeFlags());
    }
	
	/**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::setRawValue
	 * @covers WellidUsageExamples\SanitorWellidEmailExample::addSanitorMatchValidator
     */
	public function testSetRawValue() {
		$this->assertNull($this->object->getRawValue());
		$this->object->setRawValue('example@exam\ple.org');
		$this->assertEquals('example@exam\ple.org', $this->object->getRawValue());
		$this->assertTrue($this->object->validateBool());
		$this->object->setRawValue('foooo');
		$this->assertFalse($this->object->validateBool());
		$this->assertInstanceOf('WellidUsageExamples\SanitorWellidEmailExample', $this->object->addSanitorMatchValidator());
		$this->object->setRawValue('example@exam\ple.org');
		$this->assertFalse($this->object->validateBool());
	}

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::setSanitizer
     * @covers WellidUsageExamples\SanitorWellidEmailExample::__construct
     * @covers WellidUsageExamples\SanitorWellidEmailExample::addValidators
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getValidators
     */
    public function testSetSanitizer() {
        $x = new SanitorWellidEmailExample();
        $this->assertCount(2, $x->getValidators());
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::rawValueFromInput
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getRawValue
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getFilteredValue
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getValue
     */
    public function testRawValueFromInput() {
        $this->object->rawValueFromInput(\INPUT_SESSION, 'validemail');
        $this->assertEquals('mail@benedict\roeser.de', $this->object->getRawValue());
        $this->assertEquals('mail@benedictroeser.de', $this->object->getFilteredValue());
        $this->assertEquals('mail@benedictroeser.de', $this->object->getValue());
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->rawValueFromInput(\INPUT_SESSION, 'invalidemail');
        $this->assertFalse($this->object->validate()->hasPassed());
    }

}
