<?php

namespace WellidUsageExamples;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-24 at 19:20:33.
 */
class SanitorWellidEmailExampleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SanitorWellidEmailExample
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_SESSION['validemail'] = 'mail@benedict\roeser.de';
        $_SESSION['invalidemail'] = '';
        $this->object = new SanitorWellidEmailExample;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getSanitizer
     */
    public function testGetSanitizer() {
        $this->assertEquals(FILTER_SANITIZE_EMAIL, $this->object->getSanitizer()->getSanitizeFilter());
        $this->assertEquals(FILTER_NULL_ON_FAILURE, $this->object->getSanitizer()->getSanitizeFlags());
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::setSanitizer
     * @todo   Implement testSetSanitizer().
     */
    public function testSetSanitizer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::rawValueFromInput
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getRawValue
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getFilteredValue
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getValue
     */
    public function testRawValueFromInput() {
        $this->object->rawValueFromInput(\INPUT_SESSION, 'validemail');
        $this->assertEquals('mail@benedict\roeser.de', $this->object->getRawValue());
        $this->assertEquals('mail@benedictroeser.de', $this->object->getFilteredValue());
        $this->assertEquals('mail@benedictroeser.de', $this->object->getValue());
        $this->assertTrue($this->object->validate()->hasPassed());
        $this->object->rawValueFromInput(\INPUT_SESSION, 'invalidemail');
        $this->assertFalse($this->object->validate()->hasPassed());
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::setRawValue
     * @todo   Implement testSetRawValue().
     */
    public function testSetRawValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::clearValidationResult
     * @todo   Implement testClearValidationResult().
     */
    public function testClearValidationResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::disableValidationCache
     * @todo   Implement testDisableValidationCache().
     */
    public function testDisableValidationCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::isValidationCacheEnabled
     * @todo   Implement testIsValidationCacheEnabled().
     */
    public function testIsValidationCacheEnabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::validateBool
     * @todo   Implement testValidateBool().
     */
    public function testValidateBool() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::validateValue
     * @todo   Implement testValidateValue().
     */
    public function testValidateValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::addValidators
     * @todo   Implement testAddValidators().
     */
    public function testAddValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WellidUsageExamples\SanitorWellidEmailExample::getValidators
     * @todo   Implement testGetValidators().
     */
    public function testGetValidators() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
